//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""738535e8-d9b7-4272-aa87-913e1985c178"",
            ""actions"": [
                {
                    ""name"": ""LaneBlue"",
                    ""type"": ""Button"",
                    ""id"": ""7299092b-65af-4389-8aac-600d61060dfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LaneYellow"",
                    ""type"": ""Button"",
                    ""id"": ""f9d6437b-5ce3-4367-bce7-30cc8e23a695"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LaneGreen"",
                    ""type"": ""Button"",
                    ""id"": ""43dc4461-e32b-4c78-a9f7-de075933ad66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LaneRed"",
                    ""type"": ""Button"",
                    ""id"": ""6be399c8-69a5-4b33-ba28-2500ca185bb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b7fe8543-7aad-4bbe-b6b5-3efd1b324880"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9d6751d5-52de-4224-a254-dae5c9d7582b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneBlue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""378d11bf-ab8d-43ce-b627-fb3b2c268e0f"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneBlue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a91ce7fe-f9af-46c1-9db1-690096e7619f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneYellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6807298c-41c1-4a86-935f-3ce8c70039f4"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneYellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25243493-db62-4c5e-8654-5a99bd66a95b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneGreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaf7c1aa-5666-483c-b3ea-17d3f0925b98"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneGreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8f26fed-678b-4dfa-b7f6-5fa4d6fcfe4e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneRed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34eeed89-5f05-43d4-94c8-409f52195b9c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaneRed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb37bb49-64e9-492a-ae91-299d92b05926"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_LaneBlue = m_GamePlay.FindAction("LaneBlue", throwIfNotFound: true);
        m_GamePlay_LaneYellow = m_GamePlay.FindAction("LaneYellow", throwIfNotFound: true);
        m_GamePlay_LaneGreen = m_GamePlay.FindAction("LaneGreen", throwIfNotFound: true);
        m_GamePlay_LaneRed = m_GamePlay.FindAction("LaneRed", throwIfNotFound: true);
        m_GamePlay_Pause = m_GamePlay.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private List<IGamePlayActions> m_GamePlayActionsCallbackInterfaces = new List<IGamePlayActions>();
    private readonly InputAction m_GamePlay_LaneBlue;
    private readonly InputAction m_GamePlay_LaneYellow;
    private readonly InputAction m_GamePlay_LaneGreen;
    private readonly InputAction m_GamePlay_LaneRed;
    private readonly InputAction m_GamePlay_Pause;
    public struct GamePlayActions
    {
        private @Player m_Wrapper;
        public GamePlayActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @LaneBlue => m_Wrapper.m_GamePlay_LaneBlue;
        public InputAction @LaneYellow => m_Wrapper.m_GamePlay_LaneYellow;
        public InputAction @LaneGreen => m_Wrapper.m_GamePlay_LaneGreen;
        public InputAction @LaneRed => m_Wrapper.m_GamePlay_LaneRed;
        public InputAction @Pause => m_Wrapper.m_GamePlay_Pause;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void AddCallbacks(IGamePlayActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Add(instance);
            @LaneBlue.started += instance.OnLaneBlue;
            @LaneBlue.performed += instance.OnLaneBlue;
            @LaneBlue.canceled += instance.OnLaneBlue;
            @LaneYellow.started += instance.OnLaneYellow;
            @LaneYellow.performed += instance.OnLaneYellow;
            @LaneYellow.canceled += instance.OnLaneYellow;
            @LaneGreen.started += instance.OnLaneGreen;
            @LaneGreen.performed += instance.OnLaneGreen;
            @LaneGreen.canceled += instance.OnLaneGreen;
            @LaneRed.started += instance.OnLaneRed;
            @LaneRed.performed += instance.OnLaneRed;
            @LaneRed.canceled += instance.OnLaneRed;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IGamePlayActions instance)
        {
            @LaneBlue.started -= instance.OnLaneBlue;
            @LaneBlue.performed -= instance.OnLaneBlue;
            @LaneBlue.canceled -= instance.OnLaneBlue;
            @LaneYellow.started -= instance.OnLaneYellow;
            @LaneYellow.performed -= instance.OnLaneYellow;
            @LaneYellow.canceled -= instance.OnLaneYellow;
            @LaneGreen.started -= instance.OnLaneGreen;
            @LaneGreen.performed -= instance.OnLaneGreen;
            @LaneGreen.canceled -= instance.OnLaneGreen;
            @LaneRed.started -= instance.OnLaneRed;
            @LaneRed.performed -= instance.OnLaneRed;
            @LaneRed.canceled -= instance.OnLaneRed;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePlayActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);
    public interface IGamePlayActions
    {
        void OnLaneBlue(InputAction.CallbackContext context);
        void OnLaneYellow(InputAction.CallbackContext context);
        void OnLaneGreen(InputAction.CallbackContext context);
        void OnLaneRed(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
