//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/StageSelectInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @StageSelectInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @StageSelectInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""StageSelectInputActions"",
    ""maps"": [
        {
            ""name"": ""StageSelect"",
            ""id"": ""726beeed-cef0-4357-b74b-7649bdea7b54"",
            ""actions"": [
                {
                    ""name"": ""ToggleUnlockAll"",
                    ""type"": ""Button"",
                    ""id"": ""14650beb-5ff1-4899-a9d2-545ad9841ef4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""73d98f5a-f699-4461-bf8a-d2f0f8ea1474"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleUnlockAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // StageSelect
        m_StageSelect = asset.FindActionMap("StageSelect", throwIfNotFound: true);
        m_StageSelect_ToggleUnlockAll = m_StageSelect.FindAction("ToggleUnlockAll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // StageSelect
    private readonly InputActionMap m_StageSelect;
    private List<IStageSelectActions> m_StageSelectActionsCallbackInterfaces = new List<IStageSelectActions>();
    private readonly InputAction m_StageSelect_ToggleUnlockAll;
    public struct StageSelectActions
    {
        private @StageSelectInputActions m_Wrapper;
        public StageSelectActions(@StageSelectInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleUnlockAll => m_Wrapper.m_StageSelect_ToggleUnlockAll;
        public InputActionMap Get() { return m_Wrapper.m_StageSelect; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StageSelectActions set) { return set.Get(); }
        public void AddCallbacks(IStageSelectActions instance)
        {
            if (instance == null || m_Wrapper.m_StageSelectActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StageSelectActionsCallbackInterfaces.Add(instance);
            @ToggleUnlockAll.started += instance.OnToggleUnlockAll;
            @ToggleUnlockAll.performed += instance.OnToggleUnlockAll;
            @ToggleUnlockAll.canceled += instance.OnToggleUnlockAll;
        }

        private void UnregisterCallbacks(IStageSelectActions instance)
        {
            @ToggleUnlockAll.started -= instance.OnToggleUnlockAll;
            @ToggleUnlockAll.performed -= instance.OnToggleUnlockAll;
            @ToggleUnlockAll.canceled -= instance.OnToggleUnlockAll;
        }

        public void RemoveCallbacks(IStageSelectActions instance)
        {
            if (m_Wrapper.m_StageSelectActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStageSelectActions instance)
        {
            foreach (var item in m_Wrapper.m_StageSelectActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StageSelectActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StageSelectActions @StageSelect => new StageSelectActions(this);
    public interface IStageSelectActions
    {
        void OnToggleUnlockAll(InputAction.CallbackContext context);
    }
}
